### ISSUE TITLE
ISWC - editing mode doesn't become 'published'

### ISSUE THREAD

**Issue by chloedotbc** [cardstack/dotbc-bugs#23]
Summary

Edits aren't becoming published.

Steps to reproduce

1. Open works card
2. Click edit on the work title card
3. Click edit page icon
4. Enter ISWC and code
5. Press save

Expected result

1. It shows up on the card and also says "published.
2. When you refresh it disappears

Actual result

1. It shows up on the card - but stays at "edited" stage. 
2. When you refresh it disappears

Environment

Operating system: Mac OS X 10.12.6
Browser: Chrome

Additional information

**Comment by PublisherUser** [comment]
Produces console error:

"Error: The adapter rejected the commit because it was invalid
    at r.t [as constructor] (https://pouty.pizza/assets/vendor-7bc4a614ccf17f87401a0fa324b2f382.js:2428:13)
    at re (https://pouty.pizza/assets/vendor-7bc4a614ccf17f87401a0fa324b2f382.js:7708:80)
    at new r (https://pouty.pizza/assets/vendor-7bc4a614ccf17f87401a0fa324b2f382.js:7708:245)
    at e.handleResponse (https://pouty.pizza/assets/vendor-7bc4a614ccf17f87401a0fa324b2f382.js:8095:33)
    at https://pouty.pizza/assets/vendor-7bc4a614ccf17f87401a0fa324b2f382.js:8113:14
    at https://pouty.pizza/assets/vendor-7bc4a614ccf17f87401a0fa324b2f382.js:8113:90
    at e.l.error (https://pouty.pizza/assets/vendor-7bc4a614ccf17f87401a0fa324b2f382.js:8113:100)
    at l (https://pouty.pizza/assets/vendor-7bc4a614ccf17f87401a0fa324b2f382.js:477:118)
    at Object.fireWith [as rejectWith] (https://pouty.pizza/assets/vendor-7bc4a614ccf17f87401a0fa324b2f382.js:478:694)
    at x (https://pouty.pizza/assets/vendor-7bc4a614ccf17f87401a0fa324b2f382.js:750:468)"

**Comment by dnaidionov** [comment]
tracked in cardstack/dotbc#281

**Comment by dnaidionov** [comment]
This should be fixed, can you retest pls
